### ISSUE TITLE
Improve constructor injection

### ISSUE THREAD

**Issue by hantsy** [jakartaee/cdi#464]
Similiar to Spring IOC, for a component managed by CDI, if there is only one constructor with parameters, it should be injected automatically **without** an explicit `@Inject`.

```java
private final OrderRepository orders; // OrderRepository is a CDI bean

public class OrderService(OrderRepository orders){ //OrderRepository should be injected automatically here.
    this.orders = orders;
}
```

Similarly the methods of a component should be handled automatically.

**Comment by mkouba** [comment]
> Similarly the methods of a component should be handled automatically.

I agree that it makes sense for a bean class with a single constructor. However, I don't think something similar could be implemented for [initializer methods](https://docs.jboss.org/cdi/spec/2.0/cdi-spec.html#initializer_methods). You wouldn't be able to distinguish an initializer method from regular business methods of a bean.

**Comment by hantsy** [comment]
@mkouba Yeah. You are right. Most of my expereince of the method inejction in Spring is `@Bean` declaration. It seems this is equivalent to `@Produces` in CDI. 

In CDI, it could aleady work as expected.

**Comment by hantsy** [comment]
Tried with single constructors with args, but when I tested them with Arquillian.  

And I got the execption.

```bash
Caused by: org.jboss.weld.exceptions.UnproxyableResolutionException: WELD-001435: Normal scoped bean class org.eclipse.cargotracker.domain.model.handling.HandlingEventFactory is not proxyable because it has no no-args constructor - Managed Bean [class org.eclipse.cargotracker.domain.model.handling.HandlingEventFactory] with qualifiers [@Any @Default].
	at org.jboss.weld.bean.proxy.DefaultProxyInstantiator.validateNoargConstructor(DefaultProxyInstantiator.java:50)
	at org.jboss.weld.util.Proxies.getUnproxyableClassException(Proxies.java:228)
	at org.jboss.weld.util.Proxies.getUnproxyableTypeException(Proxies.java:178)
	at org.jboss.weld.bootstrap.Validator.validateInjectionPointForDeploymentProblems(Validator.java:397)
```

Currently a non-args constructor is requried to generate proxy?

**Comment by mkouba** [comment]
> Tried with single constructors with args(of course I added `@Inject` on the constructor), but when I tested them with Arquillian.
> 
> And I got the execption.
> 
> ```shell
> Caused by: org.jboss.weld.exceptions.UnproxyableResolutionException: WELD-001435: Normal scoped bean class org.eclipse.cargotracker.domain.model.handling.HandlingEventFactory is not proxyable because it has no no-args constructor - Managed Bean [class org.eclipse.cargotracker.domain.model.handling.HandlingEventFactory] with qualifiers [@Any @Default].
> 	at org.jboss.weld.bean.proxy.DefaultProxyInstantiator.validateNoargConstructor(DefaultProxyInstantiator.java:50)
> 	at org.jboss.weld.util.Proxies.getUnproxyableClassException(Proxies.java:228)
> 	at org.jboss.weld.util.Proxies.getUnproxyableTypeException(Proxies.java:178)
> 	at org.jboss.weld.bootstrap.Validator.validateInjectionPointForDeploymentProblems(Validator.java:397)
> ```
> 
> Currently a non-args constructor is requried to generate proxy?

Yes, normal scoped and intercepted beans must be proxyable, i.e. also have a no-args constructor, so that CDI containers can leverage subclassing to create proxies and intercepted subclasses.

FYI Quarkus provides [Simplified Constructor Injection](https://quarkus.io/guides/cdi-reference#simplified-constructor-injection), basically a no-args constructor is added automatically in the bytecode (if missing).

**Comment by manovotn** [comment]
Martin is correct.
I would just add that the two concepts - (1)constructor injection simplification and (2)proxyability requirement - are two different, disparate things.
The former(1) can be leveraged for non-proxied beans as well meaning you could have dependent or singleton bean that only declares singular parameterized constructor and doesn't require annotation. Obviously, with just the proposed change, you'd run into problems with proxied beans as those require dual constructors and you're back to needing `@Inject` annotation on the parameterized one so that CDI can tell which one it should use.
The latter(2) is a requirement so that the proxy class can be safely constructed without needing any kind of state. As for the optimalization Quarkus does, I am not sure it's as easily doable for runtime implementations (Quarkus is build-time and as such can alter the classes before loading them). I'd need to do some digging to find out.

**Comment by hantsy** [comment]
How Micronaut and Quarkus handle it correctly? And in the latest CDI lite, there is a Micronaut implementation.

**Comment by graemerocher** [comment]
Micronaut uses a different approach of generating byte code in the same package as the class therefore it is able to invoke the constructor of protected, package protected and public constructors directly without the hacks mentions by @JHahnHRO 

Micronaut doesn't support private constructors.

To my understanding Quarkus makes this work by transforming the byte code during the build enhancement phase and altering modifiers to make say a package private or protected constructor public even if it is not declared public. Anyone is free to correct my understanding of this approach.

**Comment by manovotn** [comment]
Quarkus can do this via bytecode transformation. Because it has a build time phase first, it can enrich those classes, generate missing constructors etc.
But you simply cannot apply this to the specification as such, especially not for any implementation that doesn't leverage build time phase.

**Comment by graemerocher** [comment]
yeah like I said I am not the expert on the Quarkus side of things

**Comment by Ladicek** [comment]
CDI Lite still requires the _bean constructor_ to be annotated `@Inject` (unless it's a zero-parameter constructor), and it still requires normal-scoped beans to always have a zero-parameter constructor.

Quarkus does 2 things that are _outside_ of the CDI specification:

1. If the bean class has a single constructor, it is assumed to be the _bean constructor_.
2. If the bean class is normal-scoped and doesn't have a zero-parameter constructor, Quarkus transforms the bytecode of the class to add the zero-parameter constructor. (There are certain cases when this is not possible.) This conceptually happens after the item 1 above, so the newly introduced zero-parameter constructor doesn't affect the "discovery" of the _bean constructor_.

It is entirely unreasonable to expect that _all_ CDI implementations will want / be able to do what Quarkus does in item 2. Therefore, the CDI specification can't really "simplify" the lookup of the _bean constructor_ by saying "if there's only one constructor, then ...", because normal-scoped beans will only have one constructor if it's the zero-parameter constructor.

My opinion is that explicit is always better than implicit, so I personally don't really like the "simplification" Quarkus does and I still annotate my _bean constructors_ with `@Inject`.

(Fun fact: there's one special case. If the desired _bean constructor_ is the zero-parameter constructor, it doesn't have to be annotated `@Inject`. In other words, if there's multiple constructors and none of them is annotated `@Inject`, then the zero-parameter constructor is selected. But that's been like that since CDI 1.0.)

**Comment by manovotn** [comment]
With the above conversation ruling out the spec ability to eliminate the need for no-arg constructor, can we close this issue @hantsy?

**Comment by hantsy** [comment]
Ok, thanks for the discussion.

**Comment by hantsy** [comment]
@manovotn But I remember CDI lite add build-time dependency injection, like the current Micronaut and Quarkus, if possible adding automatic constructor inject in CDI lite.

**Comment by Ladicek** [comment]
CDI Lite does _not_ add build-time DI. It _allows_ (but doesn't require) build-time implementations of (a subset of) CDI.

**Comment by Ladicek** [comment]
Actually I realize this is perhaps what you had in mind, so one more clarification.

CDI Lite can't require build-time implementations to work differently from runtime implementations. Code that works with build-time implementations of CDI Lite must work with runtime implementations of CDI Lite, et vice versa.

Further, CDI Lite can't even require bytecode manipulation. I'm no expert on Micronaut, but they have very different constraints when it comes to build-time manipulation of existing bytecode than Quarkus.
