### ISSUE TITLE
@Priority on producers

### ISSUE THREAD

**Issue by Ladicek** [jakartaee/cdi#556]
Now that `@Priority` can be put on anything, we could (should?) support `@Priority` on producers (methods? fields? both?).

**Comment by mkouba** [comment]
+1 for both, i.e. `@Alternative` producer methods and fields.

**Comment by graemerocher** [comment]
this is already supported in Micronaut btw

**Comment by Ladicek** [comment]
I'm not proposing this for 4.0, just figured we should have a tracker for this.

**Comment by manovotn** [comment]
> Alternatively, a producer with @Priority could be enabled even if its declaring bean is disabled, but that would likely interfere with ambiguity resolution, specialization, and probably a few other things, so I'm not exactly a fan.

Not a fan either, you need an enabled bean to have a producer discovered on it. An exception might be static producer but I'm not sure that's worth the complexity.

> Currently, an @Alternative producer "inherits" @Priority from the bean class that declares the producer. We probably want that to keep working, but if the producer declares its own @Priority, we want that to win.

Yes, I was thinking the same - this is akin to how bindings work for interceptors.

> `producer3` is enabled, selected for application, priority 2

Frankly speaking I always found this weird but I get why we want to preserve it. Would it be sensible to impose a deprecation and in some future version require that enabled producers should have the annotation on their respective method/field?
However, in this case there is still enablement via `beans.xml` which allows you per-class declaration IIRC (`<alternatives>`)...

> `producer6` is not enabled (albeit it is selected for application, priority 4)

I don't think it's even discovered because the bean declaring it isn't enabled (same for `producer5` OFC).
See [Bean Discovery](https://jakarta.ee/specifications/cdi/4.0/jakarta-cdi-spec-4.0.html#bean_discovery_steps):

> For each **enabled bean**, the container must search the class for producer methods and fields, as defined in [Producer methods](https://jakarta.ee/specifications/cdi/4.0/jakarta-cdi-spec-4.0.html#producer_method) and in [Producer fields](https://jakarta.ee/specifications/cdi/4.0/jakarta-cdi-spec-4.0.html#producer_field), including resources, and for disposer methods as defined in [Disposer methods](https://jakarta.ee/specifications/cdi/4.0/jakarta-cdi-spec-4.0.html#disposer_method), and for observer methods.

**Comment by Ladicek** [comment]
Good point about discovery. The rest of the specification is written such that it doesn't really matter whether the producer is discovered or not -- if it would be discovered, it would still be disabled.

I also realized that by allowing `@Priority` on stereotypes in CDI 4.0, we actually already allowed putting priority directly on producers, so I'm thinking any changes we do here must directly follow from existing specification. It's probably also a good idea to experiment with how existing implementations work here.

**Comment by mkouba** [comment]
> Currently, a producer is enabled if the declaring bean is enabled. We probably want to keep that? That is, if there's a producer that declares a `@Priority`, but the declaring bean is disabled, this producer will still be disabled.

Makes sense. But frankly, this combination where both the declaring bean and the producer are `@Alternative` seems weird to me.

> Currently, an @Alternative producer "inherits" @Priority from the bean class that declares the producer. We probably want that to keep working, but if the producer declares its own @Priority, we want that to win.

:+1:
