### ISSUE TITLE
Replacement for @New to force the creation of a new instance of a Bean at injection point

### ISSUE THREAD

**Issue by nhenneaux** [jakartaee/cdi#638]
I am currently migration to CDI4.0 and I was using @New annotation to force the creation of a new instance of a bean at injection point. What can be used now for such behavior?

Here is a small example on the usage I have for now. Injecting two executor services and I expect to have two different thread pools. 
```java
@ApplicationScoped
public class MyExecutorService implements ExecutorService {
}

@Singleton
public class ExecutorServiceProvider  {

    private final ExecutorService executor1;
    private final ExecutorService executor2;

    @Inject
    ExecutorServiceProvider(
        ExecutorService executor1,
        @New(MyExecutorService.class) ExecutorService executor2
    ) 
```

**Comment by Ladicek** [comment]
`@New` has been deprecated since CDI 1.1 with the suggestion to use `@Dependent` beans.

I'm not sure if your code relies on `MyExecutorService` being `@ApplicationScoped` outside of `ExecutorServiceProvider`, but if not, changing the scope of `MyExecutorService` to `@Dependent` would do what you need.

**Comment by nhenneaux** [comment]
Yes I do need the `ApplicationScoped` for the `MyExecutorService` bean, it is a thread pool and I don't want a new thread pool to be created for each new injection.

**Comment by Ladicek** [comment]
> I don't want a new thread pool to be created for each new injection

except for `ExecutorServiceProvider` ;-)

I guess you could have an "internal" `@Dependent`-scoped bean that is "wrapped" into an "external" `@ApplicationScoped MyExecutorService` bean. Or you could create the 2nd instance of `MyExecutorService` manually.

**Comment by nhenneaux** [comment]
If I use a wrapper it is quite risky I end up with several thread pools where I don't expect them. I think I'll create manually the bean but it's sad this feature have been removed even if it is not widely used.

**Comment by mkouba** [comment]
>  but it's sad this feature have been removed even if it is not widely used

Well, it got deprecated 10 yrs ago - see [CDI-170](https://issues.redhat.com/browse/CDI-170). The issue description is IMO a bit misleading because a `@New` injection point receives a bean instance that is not bound to the scope, but has dependency injection performed and _interceptors applied_ (because the `@New` bean has the same interceptor bindings).

But one of the problems I can see is that you can't use other qualifiers on a  `@New` injection point. This is not a problem for class-based beans where each bean has a different _bean class_ but a unique _bean class_ is not required for custom/synthetic beans.

I'd recommend you to use two different beans. The first would be `@ApplicationScoped`  and would represent a shared `ExecutorService`. The other one would be `@Dependent` and would represent a `ExecutorService` instantiated for each injection point. These two beans can extend a class with common logic/injection points etc. You can either use the specific type for an injection point or introduce a new qualifier for the `@Dependent` variant.

**Comment by nhenneaux** [comment]
The annotation was not annotated as `@java.lang.Deprecated` so we haven't realized it was deprecated.

Creating a new hierarchy looks a bit complex to me to assign a specific scope to the bean (`ParentExecutorService` with two childs `SingletonExecutorService` and `NewExecutorService`) but anyway I guess it's the only way for CDI without adding other complexities.

I have instantiated manually the bean to solve my problem.

**Comment by mkouba** [comment]
> The annotation was not annotated as `@java.lang.Deprecated` so we haven't realized it was deprecated.

You're right and I have no idea why. Maybe it was a JCP/Java EE requirement or something like this.

> I have instantiated manually the bean to solve my problem.

+1
